In [1]:
# import numpy as np
# import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import seaborn as sns

# import matplotlib.pyplot as plt


# from pylab import *
# import seaborn as sn 
# from sklearn import model_selection
# import statsmodels.api as sm
# from datetime import datetime
# from sklearn.decomposition import PCA

# import warnings; warnings.simplefilter('ignore')

# plt.style.use('fivethirtyeight')

# from SSA2 import SSAv3

# %matplotlib inline



from sklearn.decomposition import PCA
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.preprocessing import scale
%matplotlib inline

In [2]:
data = pd.read_csv('105v2.csv', parse_dates=True, index_col='DateTime',encoding="windows-1252") # или 106.csv
data.head(5)

,AffinityIndex,SerialNumber,H,Tmean,WmeanH,WindDirectionH(Â°),WminH,WmaxH,WmeanV,AtmosphericPressure,RelativeHumidity,TdewPoint(Â°C),WaterVaporElasticity,AbsolutusHumidity,DensityofAir,SpeedofSoundinAir
DateTime,,,,,,,,,,,,,,,,
2017-07-22 00:01:00,6,12427AMK-03,15,15.86,0.20,94.53,0.01,0.44,-0.13,750.45,100.0,15.86,17.99,14.53,1.1954,342.12
2017-07-22 00:02:00,6,12427AMK-03,15,15.88,0.28,104.28,0.15,0.53,-0.19,750.45,100.0,15.88,18.01,14.55,1.1953,342.14
2017-07-22 00:03:00,6,12427AMK-03,15,15.87,0.23,68.53,0.11,0.36,-0.19,750.45,100.0,15.87,17.99,14.54,1.1954,342.13
2017-07-22 00:04:00,6,12427AMK-03,15,15.95,0.17,47.04,0.01,0.33,-0.18,750.45,100.0,15.95,18.09,14.62,1.1950,342.18
2017-07-22 00:05:00,6,12427AMK-03,15,16.01,0.06,11.99,0.01,0.22,-0.19,750.45,100.0,16.01,18.16,14.68,1.1947,342.22

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1186390 entries, 2017-07-22 00:01:00 to 2020-04-09 23:59:00
Data columns (total 16 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   AffinityIndex         1186390 non-null  int64
 1   SerialNumber          1186390 non-null  object
 2   H                     1186390 non-null  int64
 3   Tmean                 1186390 non-null  float64
 4   WmeanH                1186390 non-null  float64
 5   WindDirectionH(Â°)    1186390 non-null  float64
 6   WminH                 1186390 non-null  float64
 7   WmaxH                 1186390 non-null  float64
 8   WmeanV                1186390 non-null  float64
 9   AtmosphericPressure   1186390 non-null  float64
 10  RelativeHumidity      1186390 non-null  float64
 11  TdewPoint(Â°C)        1186390 non-null  float64
 12  WaterVaporElasticity  1186390 non-null  float64
 13  AbsolutusHumidity     1186390 non-null  float64
 14  DensityofAir          1186390 non-null  float64
 15  SpeedofSoundinAir     1186390 non-null  float64
dtypes: float64(13), int64(2), object(1)
memory usage: 153.9+ MB

In [4]:
del data['AffinityIndex'] 
del data['SerialNumber'] 
del data['H'] 
del data['WminH'] 
del data['WmaxH'] 
del data['WindDirectionH(Â°)'] 
del data['TdewPoint(Â°C)'] 
del data['WaterVaporElasticity'] 
del data['AbsolutusHumidity'] 
del data['DensityofAir'] 
del data['SpeedofSoundinAir']

In [5]:
data = data.groupby(pd.Grouper(freq='D')).mean()  # ПЕРИОД
data

,Tmean,WmeanH,WmeanV,AtmosphericPressure,RelativeHumidity
DateTime,,,,,
2017-07-22,19.476312,1.202660,-0.122234,750.230475,77.639915
2017-07-23,20.851142,1.164227,0.055816,749.047753,68.623974
2017-07-24,20.588375,1.556807,0.220068,746.373318,77.926284
2017-07-25,21.122393,2.011374,0.133744,742.115037,77.207245
2017-07-26,21.097521,1.113449,-0.164357,744.684319,80.063233
...,...,...,...,...,...
2020-04-05,5.206268,2.944479,1.023910,761.228300,28.456948
2020-04-06,6.587525,1.797609,0.383534,752.998987,41.198309
2020-04-07,7.605675,2.314117,0.821881,752.539291,52.011658
2020-04-08,3.743463,2.990123,0.364902,754.885343,42.576580
2020-04-09,2.579199,2.019752,0.127406,761.695216,37.885826

In [6]:
data.interpolate(method='linear', inplace=True)

In [7]:
print(data.shape)
print(data.head())
data.dtypes

(993, 5)
                Tmean    WmeanH    WmeanV  AtmosphericPressure  \
DateTime
2017-07-22  19.476312  1.202660 -0.122234           750.230475
2017-07-23  20.851142  1.164227  0.055816           749.047753
2017-07-24  20.588375  1.556807  0.220068           746.373318
2017-07-25  21.122393  2.011374  0.133744           742.115037
2017-07-26  21.097521  1.113449 -0.164357           744.684319

            RelativeHumidity
DateTime
2017-07-22         77.639915
2017-07-23         68.623974
2017-07-24         77.926284
2017-07-25         77.207245
2017-07-26         80.063233

Tmean                  float64
WmeanH                 float64
WmeanV                 float64
AtmosphericPressure    float64
RelativeHumidity       float64
dtype: object

In [8]:
data = data.drop('Tmean', axis = 1)

In [9]:
scaled = scale(data, with_mean=True, with_std=True)
scaled[:10,:]

array([[-0.87357516, -0.36956224, -0.42353142, -0.09913898],
       [-0.91482554, -0.08010982, -0.55289809, -0.5823785 ],
       [-0.49346367,  0.18691021, -0.84542891, -0.08379007],
       [-0.00557028,  0.04657582, -1.31120154, -0.12232936],
       [-0.9693264 , -0.43804083, -1.0301724 ,  0.03074687],
       [-0.42213738,  0.16030426, -1.07527721, -0.79032946],
       [-0.10199723, -0.08645253, -1.35653025, -0.40572836],
       [-0.64071358, -0.25312691, -1.44150244,  0.26105536],
       [-0.91174674, -0.38039   , -1.22222255,  0.4241082 ],
       [-0.78220948, -0.66357076, -0.7830112 ,  0.87018375]])

In [10]:
model = PCA()
model.fit(scaled)
transformed = model.transform(scaled)

In [11]:
np.round(model.explained_variance_ratio_ * 100,4)

array([36.3168, 28.4658, 22.8243, 12.3931])

In [12]:
np.round(model.components_,4)

array([[ 0.7024,  0.6669, -0.2488, -0.001 ],
       [ 0.1826,  0.0351,  0.6064,  0.7731],
       [-0.1605,  0.432 ,  0.7071, -0.5364],
       [ 0.669 , -0.6061,  0.2653, -0.3386]])

In [13]:
transformed = np.round(transformed, 5)
transformed[:10,:6]

array([[-0.75458, -0.50596, -0.26574, -0.43923],
       [-0.55785, -0.95537,  0.03365, -0.51297],
       [-0.01153, -0.66102, -0.39288, -0.63936],
       [ 0.35349, -0.88913, -0.84047, -0.33842],
       [-0.7167 , -0.79333, -0.77855, -0.66671],
       [ 0.07871, -1.33453, -0.19937, -0.39726],
       [ 0.2086 , -1.15798, -0.7625 , -0.23836],
       [-0.26046, -0.79824, -1.16577, -0.74607],
       [-0.59042, -0.59316, -1.10966, -0.84728],
       [-0.798  ,  0.03176, -1.1815 , -0.62349]])

In [14]:
np.round(np.corrcoef(transformed, rowvar=False), 4)

array([[ 1.,  0., -0., -0.],
       [ 0.,  1., -0., -0.],
       [-0., -0.,  1.,  0.],
       [-0., -0.,  0.,  1.]])